"""initial commit

Revision ID: 1a02aa100f2b
Revises:
Create Date: 2025-01-16 11:36:02.735361

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1a02aa100f2b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
