"""empty message

Revision ID: 1f302ac642f5
Revises: 95c47783bcf9
Create Date: 2025-02-10 14:03:08.822844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f302ac642f5'
down_revision: Union[str, None] = '95c47783bcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_product_id', table_name='cart')
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.drop_column('cart', 'quantity')
    op.drop_column('cart', 'product_id')
    op.drop_index('ix_cartitem_cart_id', table_name='cartitem')
    op.drop_index('ix_cartitem_product_id', table_name='cartitem')
    op.create_foreign_key(None, 'cartitem', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cartitem', 'cart', ['cart_id'], ['id'])
    op.drop_index('ix_category_name', table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_index('ix_order_product_id', table_name='order')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    op.drop_column('order', 'product_id')
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_index('ix_productorder_order_id', table_name='productorder')
    op.drop_index('ix_productorder_product_id', table_name='productorder')
    op.create_foreign_key(None, 'productorder', 'order', ['order_id'], ['id'])
    op.create_foreign_key(None, 'productorder', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productorder', type_='foreignkey')
    op.drop_constraint(None, 'productorder', type_='foreignkey')
    op.create_index('ix_productorder_product_id', 'productorder', ['product_id'], unique=False)
    op.create_index('ix_productorder_order_id', 'productorder', ['order_id'], unique=False)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'quantity')
    op.add_column('order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_index('ix_order_product_id', 'order', ['product_id'], unique=False)
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.create_index('ix_cartitem_product_id', 'cartitem', ['product_id'], unique=False)
    op.create_index('ix_cartitem_cart_id', 'cartitem', ['cart_id'], unique=False)
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_index('ix_cart_product_id', 'cart', ['product_id'], unique=False)
    # ### end Alembic commands ###
