"""empty message

Revision ID: 57a73a7d753d
Revises: 7441bc61bbaa
Create Date: 2025-02-10 14:23:20.752730

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '57a73a7d753d'
down_revision: Union[str, None] = '7441bc61bbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
