"""empty message

Revision ID: 6699a6e01277
Revises: 57a73a7d753d
Create Date: 2025-02-10 14:25:41.121982

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6699a6e01277'
down_revision: Union[str, None] = '57a73a7d753d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
