"""empty message

Revision ID: 7441bc61bbaa
Revises: 1f302ac642f5
Create Date: 2025-02-10 14:22:11.890578

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '7441bc61bbaa'
down_revision: Union[str, None] = '1f302ac642f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
