"""second migrations

Revision ID: 864bc3d578cd
Revises: 1a02aa100f2b
Create Date: 2025-01-16 11:50:56.207786

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "864bc3d578cd"
down_revision: Union[str, None] = "1a02aa100f2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
