"""empty message

Revision ID: 98fbd938372c
Revises: 6699a6e01277
Create Date: 2025-02-10 14:36:45.713896

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '98fbd938372c'
down_revision: Union[str, None] = '6699a6e01277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
